// Generated by dts-bundle-generator v8.0.1

export interface MigrationOptions {
	dbPath: string;
	latestVersion: number;
}
export declare const migrate: (options: MigrationOptions) => void;

export {};
